modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/CorgiTaco/Mobifier-Enhanced-Celestials-Addon/issues"
[[mods]]
modId = "enhanced_celestials_mobifier_integration"
version = "1.0"
displayName = "Enhanced Celestials Mobifier Integration"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials-mobifier-integration"
logoFile = "icon.png"
credits = ""
authors = "Corgi Taco"
description = '''
Mobifier integration for enhanced celestials
'''
[[dependencies.enhanced_celestials_mobifier_integration]]
modId = "forge"
mandatory = true
versionRange = "[40.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enhanced_celestials_mobifier_integration]]
modId = "mobifier"
mandatory = true
versionRange = "[1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enhanced_celestials_mobifier_integration]]
modId = "enhancedcelestials"
mandatory = true
versionRange = "[2.0.6,)"
ordering = "NONE"
side = "BOTH"
